# Generated by Django 2.0.8 on 2019-01-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute_name',
            new_name='name',
        ),
    ]
