# Generated by Django 2.0.8 on 2019-02-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190130_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_dataset',
            old_name='object_type',
            new_name='object_type_name',
        ),
    ]
