# Generated by Django 2.0.8 on 2019-02-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_uploaded_dataset_object_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.TextField(default='this is a good option.'),
            preserve_default=False,
        ),
    ]
