# Generated by Django 2.0.8 on 2019-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_uploaded_dataset_meta_data_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_dataset',
            name='meta_data_facts',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
