# Generated by Django 2.0.8 on 2019-02-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20190206_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='first_applicable_object',
            field=models.TextField(default='n1'),
            preserve_default=False,
        ),
    ]
