# Generated by Django 2.0.8 on 2019-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20190212_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_dataset',
            name='datetime_column',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_dataset',
            name='object_identifiers',
            field=models.TextField(null=True),
        ),
    ]
