# Generated by Django 2.0.8 on 2019-02-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_auto_20190213_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.TextField()),
                ('object_id', models.IntegerField()),
                ('attribute_id', models.TextField()),
                ('attribute_value', models.TextField()),
                ('valid_time_start', models.IntegerField()),
                ('valid_time_end', models.IntegerField()),
                ('data_quality', models.IntegerField()),
            ],
        ),
    ]
