# Generated by Django 2.0.8 on 2019-02-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_data_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta_data_constaint',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='meta_data_constaint',
            name='simulation_model',
        ),
        migrations.RemoveField(
            model_name='object_properties',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='object_properties',
            name='first_applicable_object',
        ),
        migrations.DeleteModel(
            name='Meta_data_constaint',
        ),
        migrations.DeleteModel(
            name='Object_properties',
        ),
    ]
