# Generated by Django 2.0.8 on 2019-02-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_simulation_model_meta_data_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.TextField()),
            ],
        ),
    ]
