# Generated by Django 2.0.8 on 2019-02-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_remove_data_points_object_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_points',
            old_name='attribute_value',
            new_name='value_as_string',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='object_type',
            new_name='object_type_id',
        ),
        migrations.AddField(
            model_name='data_points',
            name='boolean_value',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='data_points',
            name='numeric_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data_points',
            name='string_value',
            field=models.TextField(null=True),
        ),
    ]
