# Generated by Django 2.0.8 on 2019-02-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_attribute_data_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_points',
            new_name='Data_point',
        ),
    ]
