# Generated by Django 2.0.8 on 2019-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_auto_20190215_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='estimated_valid_period',
            field=models.IntegerField(default=31536000),
            preserve_default=False,
        ),
    ]
