# Generated by Django 2.0.8 on 2019-02-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_attribute_estimated_valid_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='estimated_valid_period',
            new_name='expected_valid_period',
        ),
    ]
