# Generated by Django 2.0.8 on 2019-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_remove_uploaded_dataset_valid_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_types',
            name='object_icon',
            field=models.TextField(default='si-glyph-clamp'),
            preserve_default=False,
        ),
    ]
