# Generated by Django 2.0.8 on 2019-03-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_attribute_behaviour_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.IntegerField()),
                ('number_of_times_used', models.IntegerField()),
                ('used_attribute_ids', models.TextField()),
                ('used_attribute_names', models.TextField()),
                ('rule', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='behaviour_rules',
        ),
    ]
