# Generated by Django 2.0.8 on 2019-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_auto_20190323_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.TextField(default='Test Rule 1'),
            preserve_default=False,
        ),
    ]
