# Generated by Django 2.0.8 on 2019-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0028_rule_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation_model',
            old_name='description',
            new_name='objects_dict',
        ),
        migrations.RemoveField(
            model_name='simulation_model',
            name='meta_data_facts',
        ),
        migrations.RemoveField(
            model_name='simulation_model',
            name='name',
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='simulation_end_time',
            field=models.IntegerField(default=1577836800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='simulation_start_time',
            field=models.IntegerField(default=946684800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='timestep_size',
            field=models.IntegerField(default=31557600),
            preserve_default=False,
        ),
    ]
