# Generated by Django 2.0.8 on 2019-04-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0029_auto_20190401_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation_model',
            name='timestep_size',
            field=models.IntegerField(null=True),
        ),
    ]
