# Generated by Django 2.0.8 on 2019-04-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0030_auto_20190401_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='object_type_counts',
            field=models.TextField(default='{"j1_5":1}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='total_object_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
