# Generated by Django 2.0.8 on 2019-04-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0031_auto_20190402_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='rule',
            new_name='rule_text',
        ),
        migrations.AddField(
            model_name='rule',
            name='executable',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
