# Generated by Django 2.0.8 on 2019-04-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0032_auto_20190402_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='object_timelines',
            field=models.TextField(null=True),
        ),
    ]
