# Generated by Django 2.0.8 on 2019-04-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0034_simulation_model_number_of_additional_object_facts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation_model',
            old_name='object_timelines',
            new_name='timeline_visualisation_data',
        ),
    ]
