# Generated by Django 2.0.8 on 2019-04-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0035_auto_20190408_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation_model',
            name='simulation_start_time',
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='runtime_value_correction',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
