# Generated by Django 2.0.8 on 2019-04-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0036_auto_20190411_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='simulation_start_time',
            field=models.IntegerField(default=946684800),
            preserve_default=False,
        ),
    ]
