# Generated by Django 2.0.8 on 2019-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0039_simulation_model_simulation_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation_model',
            name='simulation_error',
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='attribute_errors',
            field=models.TextField(null=True),
        ),
    ]
