# Generated by Django 2.0.8 on 2019-04-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0040_auto_20190417_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation_model',
            name='runtime_value_correction',
        ),
    ]
