# Generated by Django 2.0.8 on 2019-04-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0041_remove_simulation_model_runtime_value_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='selected_attribute',
            field=models.TextField(null=True),
        ),
    ]
