# Generated by Django 2.0.8 on 2019-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0043_learned_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='learned_rule',
            name='attribute_name',
            field=models.TextField(default='Test Attribute Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learned_rule',
            name='object_type_name',
            field=models.TextField(default='Test Object Type Name'),
            preserve_default=False,
        ),
    ]
