# Generated by Django 2.0.8 on 2019-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0044_auto_20190425_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='learned_rule',
            name='specified_factors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learned_rule',
            name='valid_times',
            field=models.TextField(default=[[1072962000, 1199192400]]),
            preserve_default=False,
        ),
    ]
