# Generated by Django 2.0.8 on 2019-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0045_auto_20190427_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='learned_rule',
            name='overall_score',
            field=models.FloatField(null=True),
        ),
    ]
