# Generated by Django 2.0.8 on 2019-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0046_learned_rule_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='learned_rule',
            name='max_p_value',
            field=models.FloatField(default=0.05),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learned_rule',
            name='min_score_contribution',
            field=models.FloatField(default=0.01),
            preserve_default=False,
        ),
    ]
