# Generated by Django 2.0.8 on 2019-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0047_auto_20190506_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='learned_rule',
            name='sorted_factor_numbers',
            field=models.TextField(null=True),
        ),
    ]
