# Generated by Django 2.0.8 on 2019-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0048_learned_rule_sorted_factor_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learned_rule',
            name='sorted_factor_numbers',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learned_rule',
            name='specified_factors',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
