# Generated by Django 2.0.8 on 2019-05-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0050_attribute_object_type_of_related_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='object_type_of_related_object',
            new_name='object_type_id_of_related_object',
        ),
    ]
