# Generated by Django 2.0.8 on 2019-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0051_auto_20190513_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_point',
            name='attribute_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='object_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='value_as_string',
            field=models.TextField(db_index=True),
        ),
    ]
