# Generated by Django 2.0.8 on 2019-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0054_auto_20190515_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_point',
            name='attribute_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='object_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='valid_time_end',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='valid_time_start',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='value_as_string',
            field=models.TextField(db_index=True),
        ),
    ]
