# Generated by Django 2.0.8 on 2019-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0055_auto_20190516_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_point',
            name='numeric_value',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='string_value',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
