# Generated by Django 2.0.8 on 2019-05-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0056_auto_20190516_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='first_applicable_object',
            new_name='first_applicable_object_type',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='object_type_id_of_related_object',
            new_name='first_relation_object_type',
        ),
    ]
