# Generated by Django 2.0.8 on 2019-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0057_auto_20190523_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='all_relation_object_types',
            field=models.TextField(null=True),
        ),
    ]
