# Generated by Django 2.0.8 on 2019-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0058_attribute_all_relation_object_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='all_applicable_object_types',
            field=models.TextField(default='["j1_5","j1_8"]'),
            preserve_default=False,
        ),
    ]
