# Generated by Django 2.0.8 on 2019-06-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0060_auto_20190523_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='Calculation_rule',
        ),
    ]
