# Generated by Django 2.0.8 on 2019-06-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0061_auto_20190626_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_var_attribute_id', models.IntegerField()),
                ('condition', models.TextField()),
                ('effect', models.TextField()),
                ('effect_is_calculation', models.NullBooleanField()),
                ('is_conditionless', models.NullBooleanField()),
                ('has_probability_1', models.NullBooleanField()),
            ],
        ),
    ]
