# Generated by Django 2.0.8 on 2019-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0062_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='condition',
            new_name='effect_exec',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='effect',
            new_name='effect_text',
        ),
        migrations.AddField(
            model_name='rule',
            name='condition_exec',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='condition_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='used_attribute_ids',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='used_attribute_names',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
