# Generated by Django 2.0.8 on 2019-06-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0063_auto_20190626_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object_types',
            old_name='object_icon',
            new_name='object_type_icon',
        ),
    ]
