# Generated by Django 2.0.8 on 2019-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0064_auto_20190627_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='probability',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='standard_dev',
            field=models.FloatField(null=True),
        ),
    ]
