# Generated by Django 2.0.8 on 2019-07-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0065_auto_20190629_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='used_attribute_names',
        ),
    ]
