# Generated by Django 2.0.8 on 2019-07-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0066_remove_rule_used_attribute_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='is_timeseries_analysis',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
