# Generated by Django 2.0.8 on 2019-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0068_likelihood_fuction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likelihood_fuction',
            name='beta_distribution_a',
        ),
        migrations.RemoveField(
            model_name='likelihood_fuction',
            name='beta_distribution_b',
        ),
        migrations.AddField(
            model_name='likelihood_fuction',
            name='list_of_probabilities',
            field=models.TextField(default='[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likelihood_fuction',
            name='object_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='y_value_attributes',
            field=models.TextField(default='[{"object_number":1, "attribute_id":56}]'),
            preserve_default=False,
        ),
    ]
