# Generated by Django 2.0.8 on 2019-07-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0069_auto_20190713_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation_model',
            old_name='attribute_errors',
            new_name='rule_infos',
        ),
        migrations.RenameField(
            model_name='simulation_model',
            old_name='linegraph_data',
            new_name='simulation_data',
        ),
        migrations.RenameField(
            model_name='simulation_model',
            old_name='selected_attribute',
            new_name='triggered_rules',
        ),
        migrations.RemoveField(
            model_name='simulation_model',
            name='timeline_visualisation_data',
        ),
    ]
