# Generated by Django 2.0.8 on 2019-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0070_auto_20190715_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='just_learned_rules',
            field=models.TextField(null=True),
        ),
    ]
