# Generated by Django 2.0.8 on 2019-08-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0072_simulation_model_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='likelihood_fuction',
            name='nb_of_sim_in_which_rule_was_used',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likelihood_fuction',
            name='nb_of_simulations',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likelihood_fuction',
            name='nb_of_values_in_posterior',
            field=models.IntegerField(default=9000),
            preserve_default=False,
        ),
    ]
