# Generated by Django 2.0.8 on 2019-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0073_auto_20190807_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='changed_var_data_type',
            field=models.TextField(default='int'),
            preserve_default=False,
        ),
    ]
