# Generated by Django 2.0.8 on 2019-09-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0074_rule_changed_var_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='correct_values',
            field=models.TextField(null=True),
        ),
    ]
