# Generated by Django 2.0.8 on 2019-11-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0076_uploaded_dataset_upload_only_matched_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_point',
            name='valid_time_end',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='valid_time_start',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='simulation_model',
            name='simulation_end_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='simulation_model',
            name='simulation_start_time',
            field=models.BigIntegerField(),
        ),
    ]
