# Generated by Django 2.0.8 on 2019-12-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0078_auto_20191106_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_point',
            name='upload_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
