# Generated by Django 2.0.8 on 2020-01-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0079_data_point_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_type_id',
            field=models.TextField(db_index=True),
        ),
    ]
