# Generated by Django 2.0.8 on 2020-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0080_auto_20200108_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_point',
            name='attribute_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='numeric_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='object_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='string_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='valid_time_end',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='valid_time_start',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='data_point',
            name='value_as_string',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='data_point',
            index=models.Index(fields=['object_id'], name='collection__object__a374ab_idx'),
        ),
        migrations.AddIndex(
            model_name='data_point',
            index=models.Index(fields=['object_id', 'valid_time_start'], name='collection__object__f3833b_idx'),
        ),
        migrations.AddIndex(
            model_name='data_point',
            index=models.Index(fields=['object_id', 'attribute_id', 'string_value'], name='collection__object__7179c7_idx'),
        ),
        migrations.AddIndex(
            model_name='data_point',
            index=models.Index(fields=['object_id', 'attribute_id', 'numeric_value'], name='collection__object__a04368_idx'),
        ),
        migrations.AddIndex(
            model_name='data_point',
            index=models.Index(fields=['attribute_id', 'value_as_string'], name='collection__attribu_c67fe9_idx'),
        ),
    ]
