# Generated by Django 2.0.8 on 2020-01-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0083_simulation_model_sorted_attribute_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter_likelihood_fuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.IntegerField()),
                ('rule_id', models.IntegerField()),
                ('parameter_name', models.TextField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('list_of_probabilities', models.TextField()),
                ('nb_of_simulations', models.IntegerField()),
                ('nb_of_sim_in_which_rule_was_used', models.IntegerField()),
                ('nb_of_values_in_posterior', models.IntegerField()),
            ],
        ),
    ]
