# Generated by Django 2.0.8 on 2020-01-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0084_parameter_likelihood_fuction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter_likelihood_fuction',
            name='nb_of_sim_in_which_rule_was_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameter_likelihood_fuction',
            name='nb_of_simulations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameter_likelihood_fuction',
            name='nb_of_values_in_posterior',
            field=models.IntegerField(null=True),
        ),
    ]
