# Generated by Django 2.0.8 on 2020-01-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0085_auto_20200127_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule_parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField()),
                ('parameter_name', models.TextField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('list_of_probabilities', models.TextField()),
                ('nb_of_simulations', models.IntegerField(null=True)),
                ('nb_of_sim_in_which_rule_was_used', models.IntegerField(null=True)),
                ('nb_of_values_in_posterior', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Parameter_likelihood_fuction',
        ),
        migrations.RenameField(
            model_name='likelihood_fuction',
            old_name='rule_id',
            new_name='rule_or_parameter_id',
        ),
    ]
