# Generated by Django 2.0.8 on 2020-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0087_auto_20200127_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likelihood_fuction',
            name='nb_of_sim_in_which_rule_was_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='likelihood_fuction',
            name='nb_of_simulations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='likelihood_fuction',
            name='nb_of_values_in_posterior',
            field=models.IntegerField(null=True),
        ),
    ]
