# Generated by Django 2.0.8 on 2020-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0089_rule_used_parameter_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likelihood_fuction',
            name='rule_or_parameter_id',
        ),
        migrations.AddField(
            model_name='likelihood_fuction',
            name='parameter_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='likelihood_fuction',
            name='rule_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='likelihood_fuction',
            name='nb_of_sim_in_which_rule_was_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likelihood_fuction',
            name='nb_of_simulations',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likelihood_fuction',
            name='nb_of_values_in_posterior',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
