# Generated by Django 2.0.8 on 2020-02-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0090_auto_20200129_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation_model',
            name='just_learned_rules',
        ),
    ]
