# Generated by Django 2.0.8 on 2020-02-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0092_auto_20200208_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='data_timestamp_info',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
