# Generated by Django 2.0.8 on 2020-02-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0093_simulation_model_data_timestamp_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation_model',
            old_name='data_timestamp_info',
            new_name='data_querying_info',
        ),
    ]
