# Generated by Django 2.0.8 on 2020-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0094_auto_20200209_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('execution_order', models.TextField()),
            ],
        ),
    ]
