# Generated by Django 2.0.8 on 2020-06-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0097_simulation_model_not_used_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='validation_data',
            field=models.TextField(null=True),
        ),
    ]
