# Generated by Django 2.0.8 on 2020-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0098_simulation_model_validation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation_model',
            name='validation_data',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
