# Generated by Django 2.0.8 on 2020-07-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0099_auto_20200615_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='run_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
