# Generated by Django 2.0.8 on 2020-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0100_simulation_model_run_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='error_threshold',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='max_df_size',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='nb_of_tested_parameters',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='run_locally',
            field=models.BooleanField(default=False),
        ),
    ]
