# Generated by Django 2.0.8 on 2020-07-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0101_auto_20200710_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='nb_of_parameters_to_keep',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
