# Generated by Django 2.0.8 on 2020-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0102_simulation_model_nb_of_parameters_to_keep'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='aborted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
