# Generated by Django 2.0.8 on 2020-07-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0104_auto_20200718_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='aggregation_condition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
