# Generated by Django 2.0.8 on 2020-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0105_rule_aggregation_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='aggregation_exec',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='aggregation_text',
            field=models.TextField(null=True),
        ),
    ]
