# Generated by Django 2.0.8 on 2020-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0106_auto_20200722_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='aggregation_exec',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='aggregation_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
