# Generated by Django 2.0.8 on 2020-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0107_auto_20200723_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='condition_exec',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='condition_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
