# Generated by Django 2.0.8 on 2020-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0108_auto_20200724_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='simulation_name',
            field=models.TextField(default='New Simulation'),
            preserve_default=False,
        ),
    ]
