# Generated by Django 2.0.8 on 2020-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0110_simulation_model_limit_to_populated_y0_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logged_variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_time', models.IntegerField()),
                ('variable_name', models.TextField()),
                ('variable_value', models.TextField()),
            ],
        ),
    ]
