# Generated by Django 2.0.8 on 2020-09-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0118_auto_20200904_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likelihood_fuction',
            old_name='nb_of_values_in_posterior',
            new_name='nb_of_tested_parameters_in_posterior',
        ),
    ]
