# Generated by Django 2.0.8 on 2020-09-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0119_auto_20200907_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likelihood_fuction',
            old_name='nb_of_tested_parameters_in_posterior',
            new_name='nb_of_tested_params_in_posterior',
        ),
    ]
