# Generated by Django 2.0.8 on 2020-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0121_auto_20200907_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='likelihood_fuction',
            name='nb_of_tested_parameters',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
