# Generated by Django 2.0.8 on 2020-09-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0122_likelihood_fuction_nb_of_tested_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation_model',
            name='rule_infos',
        ),
        migrations.RemoveField(
            model_name='simulation_result',
            name='rule_infos',
        ),
    ]
