# Generated by Django 2.0.8 on 2020-09-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0123_auto_20200908_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation_model',
            name='nb_of_parameters_to_keep',
        ),
    ]
