# Generated by Django 2.0.8 on 2020-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0125_remove_simulation_model_validation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation_model',
            name='manually_set_initial_values',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
