# Generated by Django 2.0.8 on 2020-09-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0127_likelihood_fuction_execution_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likelihood_fuction',
            new_name='Likelihood_function',
        ),
    ]
