# Generated by Django 2.0.8 on 2020-10-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0128_auto_20200929_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution_order_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_order_id', models.IntegerField()),
                ('simulation_id', models.IntegerField()),
                ('score', models.FloatField()),
                ('based_of_n_simulations', models.IntegerField()),
            ],
        ),
    ]
