# Generated by Django 2.0.8 on 2020-10-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0129_execution_order_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Execution_order_score',
        ),
    ]
